name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      status: success

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from tag
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Update Cargo.toml version
        run: sed -i "s/^version = \".*\"/version = \"$VERSION\"/" Cargo.toml

      - uses: dtolnay/rust-toolchain@stable

      - uses: jetli/wasm-pack-action@v0.4.0

      - uses: Aandreba/setup-binaryen@v1.0.0
        with:
          token: ''

      - name: Build
        run: |
          wasm-pack build --target web --release --scope ${GITHUB_REPOSITORY_OWNER} --out-dir web

      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: web/

  release:
    runs-on: ubuntu-latest
    needs: build
    environment: pub
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: web/
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          working_directory: web
          files: |
            evaluator_bg.wasm
            evaluator_bg.wasm.d.ts
            evaluator.js
            evaluator.d.ts
            package.json
          fail_on_unmatched_files: true

  npm_publish:
    runs-on: ubuntu-latest
    needs: build
    environment: pub
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: web/
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
      - name: Upgrade NPM
        run: npm install -g npm@latest
      - name: Publish
        working-directory: web
        run: npm publish --provenance --access public
